document.addEventListener('DOMContentLoaded', () => {
  if (!window.THREE || !window.BPDC_LOCATIONS) return;
  const canvas = document.getElementById('pathwayCanvas');
  const numberHud = document.getElementById('pathwayNumber');
  const titleHud = document.getElementById('pathwayTitle');
  const reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const touchDevice = window.matchMedia('(hover: none), (pointer: coarse)').matches;
  const scene = new THREE.Scene();
  const camera = new THREE.PerspectiveCamera(42, innerWidth / innerHeight, .1, 100);
  const renderer = new THREE.WebGLRenderer({ canvas, alpha: true, antialias: true });
  renderer.setPixelRatio(Math.min(devicePixelRatio, 1.5)); renderer.setSize(innerWidth, innerHeight); renderer.setClearColor(0x000000, 0);
  scene.fog = new THREE.FogExp2(0x080808, .035); scene.add(new THREE.AmbientLight(0x807878, .28));
  const red = new THREE.Color(0xc24b43); const dimRed = new THREE.Color(0x4b1c1b); const pale = new THREE.Color(0xf0eee9);
  const orderedLocations = stories.map((story) => ({ story, location: BPDC_LOCATIONS[story.id] }));
  const MIN_NODE_DISTANCE = 6.5;
  const enforceMinimumDistance = (points) => { const adjusted = points.map((point) => point.clone()); for (let current = 1; current < adjusted.length; current += 1) { for (let previous = 0; previous < current; previous += 1) { const offset = adjusted[current].clone().sub(adjusted[previous]); const distance = offset.length(); if (distance >= MIN_NODE_DISTANCE) continue; const direction = distance > .001 ? offset.normalize() : new THREE.Vector3(1, .2, -.4).normalize(); adjusted[current].copy(adjusted[previous]).add(direction.multiplyScalar(MIN_NODE_DISTANCE)); } } return adjusted; };
  const locationPoints = enforceMinimumDistance(orderedLocations.map(({ location }) => new THREE.Vector3(location.x, location.y, location.z)));
  const curve = new THREE.CatmullRomCurve3(locationPoints, false, 'centripetal', .42);
  const nodeProgress = stories.map((_, index) => index / (stories.length - 1));

  const campusReference = new THREE.Group();
  const ground = new THREE.Mesh(new THREE.PlaneGeometry(18, 18), new THREE.MeshBasicMaterial({ color: 0x0c0d0d, transparent: true, opacity: .62, side: THREE.DoubleSide }));
  ground.scale.set(2.5, 2.5, 2.5); ground.rotation.x = -Math.PI / 2; ground.position.y = -2.45; campusReference.add(ground);
  const referenceMaterial = new THREE.MeshBasicMaterial({ color: 0x202020, transparent: true, opacity: .38 });
  [[-3, 1.2, 2.2, 1.2], [-.1, .6, 2.1, .9], [3.2, -.5, 1.6, 1.4], [1, -1.7, 2.4, .7], [-2.5, -1.4, 1.4, .8]].forEach(([x, z, width, depth]) => { const block = new THREE.Mesh(new THREE.BoxGeometry(width, .18, depth), referenceMaterial); block.position.set(x, -2.35, z); campusReference.add(block); });
  scene.add(campusReference);

  const pathPoints = curve.getPoints(260); const pathPositions = new Float32Array(pathPoints.length * 3); const pathColors = new Float32Array(pathPoints.length * 3);
  pathPoints.forEach((point, index) => { pathPositions[index * 3] = point.x; pathPositions[index * 3 + 1] = point.y; pathPositions[index * 3 + 2] = point.z; pathColors[index * 3] = dimRed.r; pathColors[index * 3 + 1] = dimRed.g; pathColors[index * 3 + 2] = dimRed.b; });
  const pathGeometry = new THREE.BufferGeometry(); pathGeometry.setAttribute('position', new THREE.BufferAttribute(pathPositions, 3)); pathGeometry.setAttribute('color', new THREE.BufferAttribute(pathColors, 3));
  const pathMaterial = new THREE.PointsMaterial({ size: .068, vertexColors: true, transparent: true, opacity: .92, sizeAttenuation: true, blending: THREE.AdditiveBlending }); scene.add(new THREE.Points(pathGeometry, pathMaterial));

  const nodes = []; const nodeGroup = new THREE.Group(); scene.add(nodeGroup);
  const shellGeometry = new THREE.SphereGeometry(.22, 18, 12);
  const nodeRadii = { admissions: [.78, .32, -.32], 'maha-mall': [.8, .34, .28], medical: [1.02, .4, -.48], library: [.84, .27, .08], security: [.88, .35, .54], 'student-council': [1.08, .42, -.22], mess: [.82, .34, .12] };
  const createCircularType = (story) => { const group = new THREE.Group(); const labelCanvas = document.createElement('canvas'); labelCanvas.width = 1200; labelCanvas.height = 240; const context = labelCanvas.getContext('2d'); const phrase = story.title.toUpperCase(); context.font = '600 72px Manrope, sans-serif'; context.textAlign = 'center'; context.textBaseline = 'middle'; context.fillStyle = '#f0eee9'; context.fillText(phrase, 600, 120); const texture = new THREE.CanvasTexture(labelCanvas); texture.needsUpdate = true; const [radiusX, radiusY, tilt] = nodeRadii[story.id] || [.84, .34, 0]; const textMesh = new THREE.Mesh(new THREE.PlaneGeometry(2, 1), new THREE.MeshBasicMaterial({ map: texture, transparent: true, opacity: .72, depthTest: false })); const textWidth = Math.max(1.55, Math.min(2.55, context.measureText(phrase).width / 260)); textMesh.scale.set(textWidth, .34, 1); const ellipsePoints = new THREE.EllipseCurve(0, 0, radiusX, radiusY, 0, Math.PI * 2, false, 0).getPoints(128); const guideGeometry = new THREE.BufferGeometry().setFromPoints(ellipsePoints.map((point) => new THREE.Vector3(point.x, point.y, .015))); const guide = new THREE.LineLoop(guideGeometry, new THREE.LineBasicMaterial({ color: dimRed, transparent: true, opacity: .06 })); group.rotation.x = .98; group.rotation.z = tilt; group.userData = { radiusX, radiusY, baseTilt: tilt, textMesh, guide, orbitAngle: -Math.PI / 2, orbitSpeed: story.id === 'library' ? .00006 : story.id === 'security' ? .00022 : .00014, textWidth }; group.add(guide, textMesh); return group; };
  const createCenterLabel = (story) => { const labelCanvas = document.createElement('canvas'); labelCanvas.width = 360; labelCanvas.height = 110; const context = labelCanvas.getContext('2d'); context.textAlign = 'center'; context.fillStyle = '#f0eee9'; context.font = '500 19px monospace'; context.fillText(story.title, 180, 35); context.fillStyle = '#c24b43'; context.font = '500 14px monospace'; context.fillText('OPEN STORY →', 180, 72); const sprite = new THREE.Sprite(new THREE.SpriteMaterial({ map: new THREE.CanvasTexture(labelCanvas), transparent: true, opacity: 0, depthTest: false })); sprite.scale.set(1.18, .36, 1); sprite.position.z = .34; return sprite; };
  const createNumberLabel = (story) => { const labelCanvas = document.createElement('canvas'); labelCanvas.width = 120; labelCanvas.height = 80; const context = labelCanvas.getContext('2d'); context.textAlign = 'center'; context.textBaseline = 'middle'; context.fillStyle = '#f0eee9'; context.font = '500 30px monospace'; context.fillText(story.number, 60, 40); const sprite = new THREE.Sprite(new THREE.SpriteMaterial({ map: new THREE.CanvasTexture(labelCanvas), transparent: true, opacity: .7, depthTest: false })); sprite.scale.set(.38, .25, 1); sprite.position.set(0, -.26, .34); return sprite; };
  const addUniqueDetail = (group, story) => { const material = new THREE.MeshBasicMaterial({ color: red, transparent: true, opacity: .8 }); if (story.id === 'medical') { const vertical = new THREE.Mesh(new THREE.BoxGeometry(.026, .24, .026), material); const horizontal = vertical.clone(); horizontal.rotation.z = Math.PI / 2; group.add(vertical, horizontal); } else if (story.id === 'student-council') { for (let index = 0; index < 3; index += 1) { const point = new THREE.Mesh(new THREE.SphereGeometry(.042, 8, 6), material); const angle = index * Math.PI * 2 / 3; point.position.set(Math.cos(angle) * .29, Math.sin(angle) * .29, .08); point.userData.orbitPoint = true; group.add(point); } } else if (story.id === 'security') { const sweep = new THREE.Mesh(new THREE.TorusGeometry(.43, .009, 6, 32), material); sweep.rotation.x = Math.PI / 2; sweep.visible = false; sweep.userData.securitySweep = true; group.add(sweep); } else if (story.id === 'library') { const slowLine = new THREE.Mesh(new THREE.TorusGeometry(.42, .009, 6, 32), material); slowLine.visible = false; group.add(slowLine); } };

  orderedLocations.forEach(({ story }, index) => { const group = new THREE.Group(); group.position.copy(locationPoints[index]); group.userData = { story, index }; const shell = new THREE.Mesh(shellGeometry, new THREE.MeshStandardMaterial({ color: 0x100d0d, roughness: .7, metalness: .25, emissive: 0x160606, emissiveIntensity: .35 })); const core = new THREE.Mesh(new THREE.SphereGeometry(.075, 12, 8), new THREE.MeshBasicMaterial({ color: red, transparent: true, opacity: .82 })); const circularType = createCircularType(story); const ringWidth = nodeRadii[story.id][0]; const activeOutline = new THREE.Mesh(new THREE.TorusGeometry(ringWidth + .08, .006, 6, 40), new THREE.MeshBasicMaterial({ color: red, transparent: true, opacity: 0 })); activeOutline.rotation.x = .98; activeOutline.rotation.z = nodeRadii[story.id][2]; const centerLabel = createCenterLabel(story); const numberLabel = createNumberLabel(story); addUniqueDetail(group, story); group.add(shell, core, circularType, activeOutline, centerLabel, numberLabel); nodeGroup.add(group); nodes.push({ story, group, shell, core, circularType, activeOutline, centerLabel, numberLabel, progress: nodeProgress[index], completed: false, hovered: false, hoverStarted: 0, baseTilt: nodeRadii[story.id][2] }); });

  const dustPositions = new Float32Array(70 * 3); for (let index = 0; index < 70; index += 1) { dustPositions[index * 3] = (Math.random() - .5) * 14; dustPositions[index * 3 + 1] = (Math.random() - .5) * 15; dustPositions[index * 3 + 2] = -Math.random() * 25; } const dustGeometry = new THREE.BufferGeometry(); dustGeometry.setAttribute('position', new THREE.BufferAttribute(dustPositions, 3)); scene.add(new THREE.Points(dustGeometry, new THREE.PointsMaterial({ color: 0x625b58, size: .015, transparent: true, opacity: .2 })));
  const raycaster = new THREE.Raycaster(); const pointer = new THREE.Vector2(); let hovered = null; let targetTravel = 0; let travel = 0; let mouseX = 0; let mouseY = 0; let lastActive = -1;
  const travelFromScroll = () => { const anchors = stories.map((story) => document.getElementById(`story-${story.number}`)).filter(Boolean).map((section) => section.offsetTop); if (anchors.length !== stories.length) return 0; const cameraPosition = scrollY + innerHeight * .35; if (cameraPosition <= anchors[0]) return 0; for (let index = 0; index < anchors.length - 1; index += 1) { if (cameraPosition <= anchors[index + 1]) { const span = Math.max(1, anchors[index + 1] - anchors[index]); const local = (cameraPosition - anchors[index]) / span; return (index + local) / (anchors.length - 1); } } return 1; };
  const updateHud = (index) => { const node = nodes[index]; if (!node || index === lastActive) return; lastActive = index; numberHud.textContent = `${node.story.number} / 07`; titleHud.textContent = node.story.title; document.dispatchEvent(new CustomEvent('pathway:active', { detail: node.story })); };
  const setNodeState = (node, active, time) => { const focused = active || node === hovered; node.current = active; const distanceToCamera = camera.position.distanceTo(node.group.position); const distanceVisibility = Math.max(.2, Math.min(1, 1 - Math.max(0, distanceToCamera - 4) / 25)); const scale = focused ? 1.16 : node.progress === lastActive / (nodes.length - 1) ? 1.04 : 1; node.group.scale.lerp(new THREE.Vector3(scale, scale, scale), .12); node.core.material.opacity = (focused ? 1 : .52) * distanceVisibility; node.core.scale.setScalar((node.story.id === 'medical' ? 1 + Math.sin(time * .003) * .12 : 1) * (node === hovered ? 1.2 : 1)); node.activeOutline.material.opacity = active ? .12 : 0; node.centerLabel.material.opacity = node === hovered ? 1 : 0; node.numberLabel.material.opacity = (focused ? .98 : .58) * distanceVisibility; const targetTilt = node === hovered ? node.baseTilt * .58 : node.baseTilt; node.circularType.rotation.x += (targetTilt + .98 - node.circularType.rotation.x) * .08; node.circularType.rotation.z += (targetTilt - node.circularType.rotation.z) * .08; const phrase = node.circularType.userData.textMesh; const reveal = node === hovered ? Math.min(1, Math.max(0, (time - node.hoverStarted) / 280)) : 1; phrase.material.opacity = (focused ? 1 : Math.max(.16, 1 - Math.abs(targetTravel - node.progress) * 1.35)) * reveal * distanceVisibility; const phraseScale = focused ? 1.08 : 1; phrase.scale.x += (node.circularType.userData.textWidth * phraseScale - phrase.scale.x) * .1; phrase.scale.y += (.34 * phraseScale - phrase.scale.y) * .1; };
  const updatePathColors = () => { const colors = pathGeometry.attributes.color.array; for (let index = 0; index < pathPoints.length; index += 1) { const progress = index / (pathPoints.length - 1); const nearHovered = hovered ? Math.abs(progress - hovered.progress) < .075 : false; const color = nearHovered ? new THREE.Color(.92, .16, .12) : progress < targetTravel ? new THREE.Color(.14, .03, .03) : progress < targetTravel + .13 ? red : dimRed; colors[index * 3] = color.r; colors[index * 3 + 1] = color.g; colors[index * 3 + 2] = color.b; } pathGeometry.attributes.color.needsUpdate = true; };
  const updateNodes = (time) => { let closest = 0; let progressDistance = Infinity; nodes.forEach((node, index) => { const difference = Math.abs(targetTravel - node.progress); if (difference < progressDistance) { progressDistance = difference; closest = index; } setNodeState(node, index === closest, time); }); updateHud(closest); updatePathColors(); };
  const onPointerMove = (event) => { pointer.x = (event.clientX / innerWidth) * 2 - 1; pointer.y = -(event.clientY / innerHeight) * 2 + 1; mouseX = (event.clientX / innerWidth - .5) * .4; mouseY = (event.clientY / innerHeight - .5) * .25; raycaster.setFromCamera(pointer, camera); const hits = raycaster.intersectObjects(nodes.map((node) => node.group), true); const next = hits.length ? nodes.find((node) => node.group === hits[0].object || node.group.getObjectById(hits[0].object.id)) : null; if (next !== hovered) { if (hovered) hovered.hovered = false; hovered = next; if (hovered) { hovered.hovered = true; hovered.hoverStarted = performance.now(); } document.body.classList.toggle('pathway-hover', Boolean(hovered)); if (hovered && !touchDevice) document.querySelector('.cursor-ring span').textContent = 'ENTER'; } };
  const onClick = () => { if (!hovered) return; hovered.completed = true; hovered.circularType.userData.orbitAngle = -Math.PI / 2; hovered.group.scale.setScalar(1.34); document.getElementById(`story-${hovered.story.number}`).scrollIntoView({ behavior: reducedMotion ? 'auto' : 'smooth' }); };
  window.addEventListener('pointermove', onPointerMove); window.addEventListener('click', onClick); window.addEventListener('scroll', () => { targetTravel = travelFromScroll(); }, { passive: true }); document.addEventListener('pathway:active', (event) => { const node = nodes.find((item) => item.story.id === event.detail.id); if (node) node.completed = true; });
  const resize = () => { camera.aspect = innerWidth / innerHeight; camera.updateProjectionMatrix(); renderer.setSize(innerWidth, innerHeight); renderer.setPixelRatio(Math.min(devicePixelRatio, 1.5)); }; window.addEventListener('resize', resize); targetTravel = travelFromScroll(); window.setTimeout(() => { targetTravel = travelFromScroll(); }, 0);
  const animate = (time = 0) => { requestAnimationFrame(animate); travel += (targetTravel - travel) * (reducedMotion ? .2 : .055); const pathT = Math.max(.015, Math.min(.985, travel)); const point = curve.getPoint(pathT); const tangent = curve.getTangent(pathT); const lookAt = point.clone().add(tangent.multiplyScalar(2.2)); const focus = hovered ? hovered.group.position.clone().sub(camera.position).normalize().multiplyScalar(.12) : new THREE.Vector3(); camera.position.lerp(point.clone().add(new THREE.Vector3(mouseX, mouseY, 2.7)).add(focus), .055); camera.lookAt(lookAt); nodes.forEach((node) => { const orbit = node.circularType.userData; if (!node.current && node !== hovered) orbit.orbitAngle += reducedMotion ? 0 : orbit.orbitSpeed; const angle = orbit.orbitAngle; node.circularType.position.set(Math.cos(angle) * orbit.radiusX, Math.sin(angle) * orbit.radiusY, 0); const parentQuaternion = new THREE.Quaternion(); node.circularType.getWorldQuaternion(parentQuaternion); const billboardQuaternion = parentQuaternion.invert().multiply(camera.quaternion); orbit.textMesh.quaternion.slerp(billboardQuaternion, .16); }); pathMaterial.size = hovered ? .082 : .068; updateNodes(time); renderer.render(scene, camera); }; animate();
});
