const stories = [
  { id: 'admissions', number: '01', title: 'ADMISSIONS', folder: 'admissions', images: ['IMG_7423.jpg', 'IMG_7425.jpg', 'IMG_7427.jpg'], scenes: ['Before you became a student, someone had to help get you here.', 'ADMISSIONS STAFF'] },
  { id: 'maha-mall', number: '02', title: 'MAHA MALL', folder: 'maha-mall', images: ['30a7cade-e3f4-48f2-b357-69ce6df06ad4.jpg', 'IMG_7345.jpg'], scenes: ['One of the first stops for many freshers.', 'Maha Mall is a BITS merchandise/store location where freshers can obtain things such as lab coats and coveralls.', 'Before your first experiment, someone made sure you had what you needed.'] },
  { id: 'medical', number: '03', title: 'MEDICAL ROOM', folder: 'medical', images: ['IMG_7399.jpg', 'IMG_7405.jpg', 'IMG_7409.jpg', 'IMG_7412.jpg', 'IMG_7415.jpg'], scenes: ["YOU DON'T PLAN TO NEED THIS ROOM.", 'BUT SOMEONE HAS TO BE READY WHEN YOU DO.', 'Some of the people you notice least are the people you may need most.'] },
  { id: 'library', number: '04', title: 'LIBRARY', folder: 'library', images: ['IMG_0324.jpeg', 'IMG_7337.jpg', 'IMG_7340.HEIC', 'IMG_7342.jpg', 'IMG_7344.jpg'], scenes: ['YOU SEE THE BOOKS.', 'YOU SEE THE SHELVES.', 'YOU SEE A PLACE TO STUDY.', 'BUT SOMEONE KEEPS IT ALL RUNNING.'] },
  { id: 'security', number: '05', title: 'SECURITY', folder: 'security', images: ['911b41a7-f2bc-43c6-810c-d3ad56f24390.JPG'], scenes: ['MAIN ENTRANCE', 'YOU WALK THROUGH THE GATE.', "THEY'RE ALREADY THERE.", 'EVERY MORNING. EVERY STUDENT. EVERY DAY.'] },
  { id: 'student-council', number: '06', title: 'STUDENT COUNCIL', folder: 'student-council', images: ['652076ef-cf5f-47ab-b6e2-0369e0d96dfe.jpg', 'c8b0d6e5-cc27-4c16-8110-e7785be92ec4.jpg', 'e326b4c8-ce02-4865-aef8-216d4c8ea444.jpg'], scenes: ['YOU SEE THE EVENTS.', 'YOU SEE THE ANNOUNCEMENTS.', 'YOU SEE THE ACTIVITIES.', 'BUT THERE ARE PEOPLE BEHIND THEM.'] },
  { id: 'mess', number: '07', title: 'MESS STAFF', folder: 'mess', images: ['5525511c-b070-4c5e-8918-4e08151147dd.jpg'], scenes: ['YOU ARRIVE WHEN THE FOOD IS READY.', 'THE WORK STARTED LONG BEFORE YOU DID.', "THE ROUTINE YOU DON'T NOTICE."] }
];
